### PR TITLE
navigation drawer error fix

### PR DESCRIPTION
**Pull request by mirsaidoff**
fix Navigation drawer inflation error
migrate to AndroidX

### CODE REVIEW

**Comment by tanmay380** [comment]
But it is working fine for me.

**Comment by tanmay380** [comment]
> fix Navigation drawer inflation error
> migrate to AndroidX

the problem that I'm facing is the navigation's drawer items are not clickable.

**Comment by tanmay380** [comment]
Screenshot (183)

**Comment by mirsaidoff** [comment]
@tanmay380 you should have synced the gradle files before writing the code :)

**Pull request merged**
